# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: TICRAFT.CL
site_url: https://github.com/fleivasilva/felileivas.github.io
site_author: Felipe Leiva
site_description: TICRAFT.CL es un lugar donde comparto mis experiencias y conocimientos en el mundo de la tecnología.

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - neoteroi.cards
  - neoteroi.timeline
  - neoteroi.projects

# Existing configuration
theme:
  favicon: images/favicon-32x32.png
  icon:
    repo: fontawesome/brands/git
  font:
    text: Roboto
  palette:
    scheme: dark
    primary: black
    accent: green
  name: material
  logo: images/068498cc590434cbdec4d94a96206b6c.png
  language: es
  features:
    - navigation.footer

extra_css:
  - stylesheets/custom.css
  - css/neoteroi-mkdocs.css

plugins:
  - search
  - blog

extra:
  favicon: images/favicon-32x32.png
  generator: false
  copyright: "© TICRAFT 2023"
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:felipe@ticraft.cl

nav:
    - 🏠 Home: index.md
    - 🚀️ Blog:
        - blog/index.md
    - 👨‍💻 About Me:
      - Presentacion: about_me/me/index.md
      - Contacto: mailto:felipe@ticraft.cl